//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendence
    {
        public int id { get; set; }
        public string attendfile { get; set; }
        public Nullable<int> AttTypeId { get; set; }
    
        public virtual attendtype attendtype { get; set; }
    }
}
