//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school
{
    using System;
    using System.Collections.Generic;
    
    public partial class homework
    {
        public int id { get; set; }
        public string taskname { get; set; }
        public string taskdetails { get; set; }
        public string taskfile { get; set; }
        public Nullable<int> CourseId { get; set; }
        public int semesterid { get; set; }
    
        public virtual course course { get; set; }
        public virtual Schoolsemester Schoolsemester { get; set; }
    }
}
