//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent
    {
        public int id { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string confirmpass { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string nationalid { get; set; }
        public Nullable<int> genderlid { get; set; }
        public Nullable<int> cityid { get; set; }
    
        public virtual parentcity parentcity { get; set; }
        public virtual SchoolGender SchoolGender { get; set; }
    }
}
